CREATE OR REPLACE FUNCTION GET_INSTRUCTOR_PROFILE(INSTRUCTOR_NAME STRING)
RETURNS TABLE (
    INSTRUCTOR STRING,
    COURSE_NAME STRING,
    CATEGORY STRING,
    TOTAL_STUDENTS INT,
    AVG_ENGAGEMENT_SCORE NUMBER(38,6),
    TOTAL_TIME_SPENT BIGINT,
    ACTIVITY_COUNT BIGINT
)
LANGUAGE SQL
AS
$$
    SELECT 
        C.INSTRUCTOR,
        C.COURSE_NAME,
        C.CATEGORY,
        COUNT(DISTINCT F.STUDENT_ID) AS TOTAL_STUDENTS,
        AVG(F.ENGAGEMENT_SCORE) AS AVG_ENGAGEMENT_SCORE,
        SUM(F.TOTAL_TIME_SPENT) AS TOTAL_TIME_SPENT,
        SUM(F.ACTIVITY_COUNT) AS ACTIVITY_COUNT
    FROM GOLD.DIM_COURSE C
    JOIN GOLD.FACT_ENGAGEMENT_SUMMARY F 
        ON C.COURSE_ID = F.COURSE_ID
    WHERE C.INSTRUCTOR = INSTRUCTOR_NAME
      AND C.COURSE_IS_CURRENT = TRUE
    GROUP BY C.INSTRUCTOR, C.COURSE_NAME, C.CATEGORY
$$;
