
-- FACT_ENGAGEMENT_SUMMARY
CREATE OR REPLACE TABLE GOLD.FACT_ENGAGEMENT_SUMMARY (
    STUDENT_ID INTEGER,
    COURSE_ID INTEGER,
    TOTAL_TIME_SPENT BIGINT,       
    ACTIVITY_COUNT BIGINT,        
    ENGAGEMENT_SCORE BIGINT,       
    LAST_ACTIVITY TIMESTAMP,       
    DAYS_INACTIVE INTEGER,
    STATUS STRING
);

-- FACT_ENROLLMENT
CREATE OR REPLACE TABLE GOLD.FACT_ENROLLMENT (
    ENROLLMENT_ID STRING PRIMARY KEY,
    STUDENT_ID STRING,
    COURSE_ID STRING,
    ENROLLMENT_DATE DATE,
    ENROLL_IS_CURRENT BOOLEAN
);

-- DIM_STUDENT
CREATE OR REPLACE TABLE GOLD.DIM_STUDENT (
    STUDENT_ID INTEGER PRIMARY KEY, 
    NAME STRING,
    EMAIL STRING,
    SIGNUP_DATE DATE,
    LOCATION STRING,
    STUDENT_IS_CURRENT BOOLEAN
);

-- DIM_COURSE
CREATE OR REPLACE TABLE GOLD.DIM_COURSE (
    COURSE_ID INTEGER PRIMARY KEY,   
    COURSE_NAME STRING,
    CATEGORY STRING,
    INSTRUCTOR STRING,
    LAUNCH_DATE DATE,
    COURSE_DURATION INTEGER,
    COURSE_IS_CURRENT BOOLEAN
);